### ISSUE TITLE
Last release lacks APK

### ISSUE THREAD

**Issue by IzzySoft** [bubelov/coins-android#2]
The last release in `releases/` (v1.8.3) is lacking the `.apk` file. Could you please attach it? Thanks!

**Comment by bubelov** [comment]
@IzzySoft Attached it. I didn't think that anyone uses it since it is available on Google Play.

**Comment by IzzySoft** [comment]
Thanks! Yeah, there are people not using Play – either because it's blocked in their country, or because they don't want it. They often use F-Droid as (one) alternative, and in that case can find your app [here in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.bubelov.coins) :wink:

Btw: What license is your app using?

**Comment by bubelov** [comment]
@IzzySoft That's a good point. Unfortunately this app has a dependency on Google Play Services so I guess It wouldn't work so well on customized versions of Android. I'll consider other options in the future.

Regarding license: no license yet, I'll pick something with no restrictions and no responsibility.

**Comment by IzzySoft** [comment]
@bubelov oh, for that there's always [microG](https://microg.org/) – as long as you don't rely on license check (`vending.CHECK_LICENSE`) or ad stuff :wink:

When you decided on (and placed) a license, please let me know so I can update the record in my repo. Just a short reply on this issue will do.

**Comment by IzzySoft** [comment]
License updated, thanks again!
