### ISSUE TITLE
Donate on fdroid metadata

### ISSUE THREAD

**Issue by ghost** [bubelov/coins-android#46]
@bubelov 
* **without your explicit consent** Donate ```https://btcmap.org/support-us``` from https://github.com/teambtcmap/btcmap-android#support-btc-map was updated by me in [fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.btcmap.yml)
* fdroid [policy](https://gitlab.com/fdroid/admin/-/issues/417) and [suggestion](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13549#note_1508711371) wrt to adding AuthorEmail, AuthorWebSite, Donate, etc..
* should i remove it?

**Comment by bubelov** [comment]
@jindam-vani  it looks fine, thanks for adding that link!
